services:

    postgres:
        image: postgres
        env_file: .env
        volumes:
            - ./postgres/create_second_db.sql:/docker-entrypoint-initdb.d/create_second_db.sql

    airflow:
        build: ./airflow
        restart: always
        env_file: .env
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./airflow/ontop-cli-4.1.0:${R2RML_CLI_DIR}
            - ./airflow/dags:/usr/local/airflow/dags
            - ./input:${R2RML_DATA_DIR}/input
            - ./upload_config.yaml:/usr/local/airflow/upload_config.yaml
        ports:
            - 8080:8080
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    graphdb:
        image: jvsoest/graphdb-free:fairstation
        ports: 
            - 7200:7200
        environment:
            - GDB_HEAP_SIZE=2g
            - GDB_MIN_MEM=1g
            - GDB_MAX_MEM=2g
