coral_test:
  study_oid: S_DEFAULTS1
  study_identifier: coral_test
  event_oid: SE_GENERIC_COLLECTION
  form_oid: F_PROTRAIT_GEN_2
  item_group_oid: IG_PROTR_GEN
  identifier_colname: id
  birthdate_colname: GEN_YEAR_BIRTH
  birthdate_isyear: TRUE
  gender_colname: GEN_GENDER
  item_prefix: I_PROTR_
  query: |
    prefix ncit:<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
    prefix roo: <http://www.cancerdata.org/roo/>
    prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    prefix xsd: <http://www.w3.org/2001/XMLSchema#>
    

    select 
    ?patient 
    ?clinT 
    ?clinN 
    ?clinM 
    ?overallStage 
    ?diagnosisDate 
    ?vitalStatusDate 
    ?vitalStatus


    where {
    	?patient a ncit:C16960 ;
            roo:P100008 ?diseaseObj ;
            roo:P100028 ?vitalStatusObj.
    
        # Vital status
    	?vitalStatusObj roo:local_value ?vital_status.
    
        # Disease
        ?diseaseObj roo:P100025 ?overallStageObj ;
            roo:P100244 ?clinTObj ;
            roo:P100242 ?clinNObj ;
            roo:P100241 ?clinMObj ;
            roo:P100251 ?diagnosisDateObj.
    
        # Overall stage
        ?overallStageObj a ncit:C28108 ;
            roo:local_value ?stage.
    
        # Tstage
        ?clinTObj a ncit:C48885 ;
            roo:local_value ?t.
        
        # Nstage
        ?clinNObj a ncit:C48884 ;
            roo:local_value ?n.
    
        # Mstage
        ?clinMObj a ncit:C48883 ;
            roo:local_value ?m.
    
        # Diagnosis date
        ?diagnosisDateObj a ncit:C25164 ;
            roo:local_value ?date_of_diagnosis.
    }
